[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Loïc Carr <zizou.xena@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.22"
itertools = "0.9.0"
regex = "1.4.2"
rayon = "1.5.0"
